### ISSUE TITLE
Spanish Support?

### ISSUE THREAD

**Issue by henleygarcia** [mikeyaworski/Automated-Bing-Searches#1]
Hello,

If you need help translating this to Spanish I don't mind helping out 👍

**Comment by mikeyaworski** [comment]
Sure, if you want to make a PR adding internationalization, I'd be open to that

**Comment by henleygarcia** [comment]
Please check the PR I made for Spanish support unless you have another thing in mind for this.

**Comment by mikeyaworski** [comment]
Linking for reference: https://github.com/mikeyaworski/Automated-Bing-Searches/pull/2
