### ISSUE TITLE
Support for multiple accounts

### ISSUE THREAD

**Issue by udithap** [mikeyaworski/Automated-Bing-Searches#16]
A family can have a maximum of 6 accounts. Could Automated-Bing-Searches natively support more than one account?

**Comment by mikeyaworski** [comment]
I think this would make the extension overreaching.

1. There would be security issues with storing a user's cookies (or worse, username/password directly) for each account.
2. It would make the extension much more complex.

My recommendation is to make multiple browser accounts on Edge where each is signed into a different profile. Then just open all of them and run the extension on each one. You shouldn't have to sign out/sign in every time. This may be possible to automate using a macro as well.
