### ISSUE TITLE
[feature request] Change to Mobile User-Agent to get Mobile scores too

### ISSUE THREAD

**Issue by yazdipour** [mikeyaworski/Automated-Bing-Searches#8]
Currently, Using this extension <https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg> I change my Browser User-Agent to Android so that I get the 120 mobile search scores.

It would have been great if you could add Auto User-Agent changer inside the extension.

**Comment by mikeyaworski** [comment]
That's a good idea! I'll get to this in the coming weeks when I have some time.
