### ISSUE TITLE
Official Microsoft rewards extension breaks after doing auto mobile searches 

### ISSUE THREAD

**Issue by jwarr111** [mikeyaworski/Automated-Bing-Searches#9]
title ^^^^^^
All of the text is way too large after ticking and using the "Also do mobile searches (doubles searches)" option. Fixed by doing auto non-mobile searches. 
Idk how easy this is to fix but i thought you should know :)

**Comment by mikeyaworski** [comment]
Well we are spoofing the header on all requests to Bing.com, so it returns the mobile site to you instead of the desktop one. That's why it will look weird, but that shouldn't really matter.

Could you provide a screenshot just in case it's something else?

**Comment by mikeyaworski** [comment]
I believe this issue has been solved in the following commits:

- 5d6b6b67874c1bd6ee493377b2d0208eab87b8e3
- 8928ea80871a475cea7098193c6a80d4f5ea4255

So I'm closing this, but the extension has been updated, so please try it out and feel free to re-open the issue if it's not actually been solved.
